pipeline {
    agent any
    stages {
        stage ('--- limpar ---') {
            steps {
                sh "echo 'mvn clean'"
            }
        }

        stage ('--- testar ---') {
            steps {
                //sh "echo 'Teste $date' >> teste.tx"
                sh "echo 'teste 0'"
                //sh "echo 'teste 1'"
                //sh "echo 'teste 2'"
            }
        }
        
        stage ('--- empacotar ---') {
            steps {
                sh "echo 'pacote'"
            }
        }
        
    }
}
